# Generated by Django 3.1.5 on 2021-04-18 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='csvhistory',
            old_name='contract',
            new_name='csv',
        ),
    ]
