# Generated by Django 3.1.5 on 2021-04-23 03:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('listing', '0002_auto_20210418_0934'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CsvHistory',
            new_name='ExportHistory',
        ),
        migrations.RenameField(
            model_name='exporthistory',
            old_name='csv',
            new_name='export',
        ),
    ]
