# Generated by Django 3.1.5 on 2021-04-06 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_tradersalescontract_memo'),
    ]

    operations = [
        migrations.AddField(
            model_name='hallpurchasescontract',
            name='memo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
