# Generated by Django 3.1.5 on 2021-04-06 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0003_auto_20210406_0142'),
        ('contracts', '0003_hallpurchasescontract_memo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PurchaseSender',
            new_name='TraderPurchasesSender',
        ),
        migrations.RenameModel(
            old_name='SaleSender',
            new_name='TraderSalesSender',
        ),
    ]
