# Generated by Django 3.1.5 on 2021-04-07 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_auto_20210406_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractproduct',
            name='status',
            field=models.CharField(choices=[('D', 'Done'), ('P', 'Pending')], default='P', max_length=1),
        ),
    ]
