# Generated by Django 3.1.5 on 2021-04-07 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0006_inventoryproduct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventoryproduct',
            old_name='management_id',
            new_name='mid',
        ),
        migrations.RenameField(
            model_name='inventoryproduct',
            old_name='receipt_date',
            new_name='purchase_date',
        ),
        migrations.RenameField(
            model_name='inventoryproduct',
            old_name='sender',
            new_name='supplier',
        ),
    ]
