# Generated by Django 3.1.5 on 2021-04-07 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0007_auto_20210407_0658'),
    ]

    operations = [
        migrations.RenameField(
            model_name='traderpurchasescontract',
            old_name='payment_due_date',
            new_name='removal_date',
        ),
        migrations.RemoveField(
            model_name='traderpurchasescontract',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='traderpurchasescontract',
            name='shipping_method',
        ),
        migrations.AddField(
            model_name='traderpurchasescontract',
            name='frame_color',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='traderpurchasescontract',
            name='receipt',
            field=models.CharField(default='', max_length=100),
        ),
    ]
