# Generated by Django 3.1.5 on 2021-04-07 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0008_auto_20210407_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traderpurchasescontract',
            name='frame_color',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='traderpurchasescontract',
            name='receipt',
            field=models.CharField(max_length=100),
        ),
    ]
