# Generated by Django 3.1.5 on 2021-04-07 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0009_auto_20210407_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='traderpurchasessender',
            name='contract',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='senders', to='contracts.traderpurchasescontract'),
        ),
    ]
