# Generated by Django 3.1.5 on 2021-04-07 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0010_traderpurchasessender_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traderpurchasessender',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='senders', to='contracts.traderpurchasescontract'),
        ),
    ]
