# Generated by Django 3.1.5 on 2021-04-07 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0011_auto_20210407_1134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hallpurchasescontract',
            old_name='insurance_fee_include',
            new_name='fee_included',
        ),
        migrations.RenameField(
            model_name='hallsalescontract',
            old_name='insurance_fee_include',
            new_name='fee_included',
        ),
    ]
