# Generated by Django 3.1.5 on 2021-04-08 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0012_auto_20210407_1229'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InventoryProduct',
        ),
    ]
