# Generated by Django 3.1.5 on 2021-04-09 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0013_delete_inventoryproduct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contractdocumentfee',
            old_name='number_of_models',
            new_name='model_count',
        ),
        migrations.RenameField(
            model_name='contractdocumentfee',
            old_name='number_of_units',
            new_name='unit_count',
        ),
    ]
