# Generated by Django 3.1.5 on 2021-04-11 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0014_auto_20210409_0358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='traderpurchasescontract',
            old_name='insurance_fee',
            new_name='fee',
        ),
        migrations.RenameField(
            model_name='tradersalescontract',
            old_name='insurance_fee',
            new_name='fee',
        ),
    ]
