# Generated by Django 3.1.5 on 2021-04-12 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0015_auto_20210411_0412'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hallpurchasescontract',
            old_name='insurance_fee',
            new_name='fee',
        ),
        migrations.RenameField(
            model_name='hallsalescontract',
            old_name='insurance_fee',
            new_name='fee',
        ),
        migrations.RemoveField(
            model_name='hallpurchasescontract',
            name='fee_included',
        ),
        migrations.RemoveField(
            model_name='hallsalescontract',
            name='fee_included',
        ),
    ]
