# Generated by Django 3.1.5 on 2021-04-17 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0006_auto_20210408_1756'),
        ('contracts', '0016_auto_20210412_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traderpurchasescontract',
            name='account_holder',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='traderpurchasescontract',
            name='account_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='traderpurchasescontract',
            name='bank_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='traderpurchasescontract',
            name='branch_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='traderpurchasescontract',
            name='fee',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='traderpurchasescontract',
            name='frame_color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='traderpurchasescontract',
            name='person_in_charge',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='traderpurchasescontract',
            name='receipt',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='traderpurchasescontract',
            name='removal_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='traderpurchasescontract',
            name='shipping_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='traderpurchasescontract',
            name='transfer_deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='traderpurchasessender',
            name='desired_arrival_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='traderpurchasessender',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='masterdata.sender'),
        ),
        migrations.AlterField(
            model_name='traderpurchasessender',
            name='shipping_company',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tradersalescontract',
            name='fee',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tradersalescontract',
            name='payment_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tradersalescontract',
            name='person_in_charge',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tradersalescontract',
            name='shipping_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tradersalessender',
            name='expected_arrival_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tradersalessender',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='masterdata.sender'),
        ),
    ]
