# Generated by Django 3.1.5 on 2021-04-17 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0017_auto_20210417_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractdocumentfee',
            name='model_count',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='contractdocumentfee',
            name='unit_count',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='amount',
            field=models.PositiveIntegerField(),
        ),
    ]
