# Generated by Django 3.1.5 on 2021-04-17 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0006_auto_20210408_1756'),
        ('contracts', '0018_auto_20210417_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hallpurchasescontract',
            name='confirmor',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='hallpurchasescontract',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='masterdata.customer'),
        ),
        migrations.AlterField(
            model_name='hallpurchasescontract',
            name='fee',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hallpurchasescontract',
            name='hall',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='masterdata.hall'),
        ),
        migrations.AlterField(
            model_name='hallpurchasescontract',
            name='opening_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hallpurchasescontract',
            name='person_in_charge',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='hallpurchasescontract',
            name='shipping_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hallpurchasescontract',
            name='transfer_account',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hallsalescontract',
            name='confirmor',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='hallsalescontract',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='masterdata.customer'),
        ),
        migrations.AlterField(
            model_name='hallsalescontract',
            name='fee',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hallsalescontract',
            name='hall',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='masterdata.hall'),
        ),
        migrations.AlterField(
            model_name='hallsalescontract',
            name='opening_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hallsalescontract',
            name='person_in_charge',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='hallsalescontract',
            name='shipping_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hallsalescontract',
            name='transfer_account',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
