# Generated by Django 3.1.5 on 2021-04-18 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0019_auto_20210417_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestone',
            name='amount',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
