# Generated by Django 3.1.5 on 2021-06-12 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0020_auto_20210418_0836'),
    ]

    operations = [
        migrations.CreateModel(
            name='TraderLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.traderpurchasescontract')),
                ('sale_contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.tradersalescontract')),
            ],
        ),
    ]
