# Generated by Django 3.1.5 on 2021-06-13 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0021_traderlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='traderlink',
            name='report_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
