# Generated by Django 3.1.5 on 2021-06-15 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0023_auto_20210613_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='hallpurchasescontract',
            name='income_print_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hallpurchasescontract',
            name='outcome_print_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hallsalescontract',
            name='income_print_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hallsalescontract',
            name='outcome_print_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='traderpurchasescontract',
            name='income_print_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='traderpurchasescontract',
            name='outcome_print_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tradersalescontract',
            name='income_print_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tradersalescontract',
            name='outcome_print_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
