# Generated by Django 3.1.5 on 2021-06-15 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0024_auto_20210615_1157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hallpurchasescontract',
            old_name='income_print_date',
            new_name='purchase_print_date',
        ),
        migrations.RenameField(
            model_name='hallpurchasescontract',
            old_name='outcome_print_date',
            new_name='purchase_print_date_expense',
        ),
        migrations.RenameField(
            model_name='hallsalescontract',
            old_name='income_print_date',
            new_name='sale_print_date',
        ),
        migrations.RenameField(
            model_name='hallsalescontract',
            old_name='outcome_print_date',
            new_name='sale_print_date_income',
        ),
        migrations.RenameField(
            model_name='traderpurchasescontract',
            old_name='income_print_date',
            new_name='purchase_print_date',
        ),
        migrations.RenameField(
            model_name='traderpurchasescontract',
            old_name='outcome_print_date',
            new_name='purchase_print_date_expense',
        ),
        migrations.RenameField(
            model_name='tradersalescontract',
            old_name='income_print_date',
            new_name='sale_print_date',
        ),
        migrations.RenameField(
            model_name='tradersalescontract',
            old_name='outcome_print_date',
            new_name='sale_print_date_income',
        ),
    ]
