# Generated by Django 3.1.5 on 2021-06-16 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0025_auto_20210615_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractproduct',
            name='report_date',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
