# Generated by Django 3.1.5 on 2021-06-16 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0026_contractproduct_report_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traderlink',
            name='report_date',
        ),
        migrations.AddField(
            model_name='traderlink',
            name='purchase_same_order',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='traderlink',
            name='sale_same_order',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
