# Generated by Django 3.1.5 on 2021-06-30 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0027_auto_20210617_0126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hallpurchasescontract',
            name='purchase_print_date_expense',
        ),
        migrations.RemoveField(
            model_name='hallsalescontract',
            name='sale_print_date_income',
        ),
    ]
