# Generated by Django 3.1.5 on 2021-07-01 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0028_auto_20210630_2312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traderpurchasescontract',
            name='purchase_print_date_expense',
        ),
        migrations.RemoveField(
            model_name='tradersalescontract',
            name='sale_print_date_income',
        ),
    ]
