# Generated by Django 3.1.5 on 2021-07-20 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0030_auto_20210720_1006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traderpurchasescontract',
            name='payment_due_date',
        ),
        migrations.RemoveField(
            model_name='traderpurchasescontract',
            name='shipping_method',
        ),
    ]
