# Generated by Django 3.1.5 on 2021-07-20 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0031_auto_20210720_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='traderpurchasescontract',
            name='payment_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='traderpurchasescontract',
            name='shipping_method',
            field=models.CharField(blank=True, choices=[('D', 'Delivery'), ('R', 'Receipt'), ('C', 'ID Change'), ('B', '* Blank')], max_length=1, null=True),
        ),
    ]
