# Generated by Django 3.2.3 on 2021-07-30 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0032_auto_20210720_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='hallpurchasescontract',
            name='available',
            field=models.CharField(blank=True, default='T', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='hallsalescontract',
            name='available',
            field=models.CharField(blank=True, default='T', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='traderpurchasescontract',
            name='available',
            field=models.CharField(blank=True, default='T', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='tradersalescontract',
            name='available',
            field=models.CharField(blank=True, default='T', max_length=1, null=True),
        ),
    ]
