# Generated by Django 3.1.5 on 2021-03-30 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentfee',
            name='name',
        ),
        migrations.AddField(
            model_name='documentfee',
            name='type',
            field=models.CharField(choices=[('P', 'Pachinko'), ('S', 'Slot')], default='P', max_length=1),
        ),
    ]
