# Generated by Django 3.1.5 on 2021-04-06 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
        ('masterdata', '0002_auto_20210330_0643'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Receiver',
            new_name='Sender',
        ),
    ]
