# Generated by Django 3.1.5 on 2021-04-08 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0003_auto_20210406_0142'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('identifer', models.IntegerField()),
                ('purchase_date', models.DateField()),
                ('supplier', models.CharField(max_length=200)),
                ('person_in_charge', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('amount', models.IntegerField()),
            ],
        ),
    ]
