# Generated by Django 3.1.5 on 2021-04-08 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0004_inventoryproduct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventoryproduct',
            old_name='identifer',
            new_name='identifier',
        ),
    ]
