# Generated by Django 3.1.5 on 2021-04-08 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0005_auto_20210408_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryproduct',
            name='identifier',
            field=models.CharField(max_length=20),
        ),
    ]
