# Generated by Django 3.1.5 on 2021-04-23 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0006_auto_20210408_1756'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='csv',
            new_name='excel',
        ),
    ]
