# Generated by Django 3.1.5 on 2021-05-06 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0008_personincharge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personincharge',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
