# Generated by Django 3.1.5 on 2021-05-09 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0010_auto_20210510_0033'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InventoryProduct',
        ),
        migrations.RemoveField(
            model_name='product',
            name='amount',
        ),
        migrations.AlterField(
            model_name='personincharge',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
