# Generated by Django 3.1.5 on 2021-05-10 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0011_auto_20210510_0717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
    ]
