# Generated by Django 3.1.5 on 2021-06-28 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0013_auto_20210626_0749'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_frigana',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='hall',
            name='customer_frigana',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sender',
            name='customer_frigana',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
