# Generated by Django 3.1.5 on 2021-07-14 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0014_auto_20210628_0818'),
    ]

    operations = [
        migrations.AddField(
            model_name='sender',
            name='excel',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
