# Generated by Django 3.1.5 on 2021-07-20 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0015_sender_excel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='excel',
        ),
        migrations.RemoveField(
            model_name='sender',
            name='excel',
        ),
    ]
