# Generated by Django 3.1.5 on 2021-07-20 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0016_auto_20210720_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='excel',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sender',
            name='excel',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
